name: Publish to NuGet

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    if: github.repository == 'BLM16/Tokenized-Calculator'
    
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build
        with:
          configuration: Release

      # Get the Release's name and strip the v from vx.x.x
      - name: Parse Version
        id: parse-version
        run: |
          version=${release:1}
          echo "::set-output name=version::$version"
        shell: bash
        env:
          release: ${{ github.event.release.name }}

      - name: Push to NuGet.org
        run: dotnet nuget push ./Calculator/bin/Release/BLM16.Util.Calculator.${{ steps.parse-version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
